
###
POST http://localhost:7007/api/u/registeruser
Content-Type: application/json

{
 "username": "Ronald_Reagan",
 "password": "the greatest president defeating communists with facts and logic!"
}
###
