POST http://localhost:7007/hotel
Content-Type: application/json

{
  "name": "Bob the building",
  "address": "we did it!",
  "rooms": [
    {
      "number": 1939,
      "price": 6000000
    }
  ]
}
###
PUT http://localhost:7007/hotel/4
Content-Type: application/json

{
  "name": "Bob the buildings",
  "address": "we did it!",
  "rooms": [
    {
      "number": 1939,
      "price": 6000000
    }
  ]
}
###
DELETE http://localhost:7007/hotel/5
###


